# GitHub Sponsors funding options
github: sejalsheth

# PayPal funding option
# paypal: integratewithtech

# Custom funding URLs (you can add multiple)
custom: 
  - https://paypal.me/Integratewithtech